# GNU make / gcc Makefile for building Pd lib / project

# Build targets and rules are defined in ../includes/libbuildrules.mk


################################################################################


LIBNAME := cyclone
CLASSNAMES := delay~ MouseState Scope~ svf~


################################################################################


include ../includes/libbuildrules.mk
