# GNU make / gcc Makefile for building Pd lib / project

# Build targets and rules are defined in ../includes/libbuildrules.mk


################################################################################


LIBNAME := zexy
CLASSNAMES := limiter~ z~


################################################################################


include ../includes/libbuildrules.mk
