# GNU make / gcc Makefile for building Pd lib / project

# Build targets and rules are defined in ../includes/libbuildrules.mk


################################################################################


LIBNAME := hcs
CLASSNAMES := canvas_name split_path sys_gui window_name


################################################################################


include ../includes/libbuildrules.mk
